### ISSUE TITLE
Investigate glove norms

### ISSUE THREAD

**Issue by Gullesnuffs** [Gullesnuffs/Codenames#7]
"gotta" is a terrible clue. Maybe it has low norm also, because it doesn't mean very much? Let's make the program print the norms and see if we can make out anything from them.

**Comment by Gullesnuffs** [comment]
or maybe we can identify useless words by their being near, say, the empty string.

**Comment by simonlindholm** [comment]
52e19247c35ea71bea85e97550ebba50ea2dea0e

Seems to help a bit, I think?

conceptnet sometimes gives similarly bad clues, but does not have norms... It could steal them from glove, or use the empty string thing maybe.
